register:
  path: /register
  controller: App\Controller\AuthController::register
  methods: POST
add_user:
  path: /api/user/add
  controller: App\Controller\AuthController::register
  methods: POST

api_login_check:
  path: /api/login_check
  controller: App\Controller\AuthController::getTokenUser

test:
  path: /api/test
  controller: App\Controller\ApiController::test

## student end point declaration ##
##
##
student_get_detail:
  path: /student/api/user/get-user/detail
  controller: App\Controller\UserController::getUserInfo
  methods: GET

## teacher end point declaration ##
##
##
teacher_get_detail:
  path: /teacher/api/user/get-user/detail
  controller: App\Controller\UserController::getUserInfo
  methods: GET

## teacher end point declaration ##
##
##
parent_get_detail:
  path: /parent/api/user/get-user/detail
  controller: App\Controller\UserController::getUserInfo
  methods: GET
