register:
  path: /register
  controller: App\Controller\AuthController::register
  methods: POST
add_user:
  path: /api/user/add
  controller: App\Controller\AuthController::register
  methods: POST

api_login_check:
  path: /api/login_check
  controller: App\Controller\AuthController::getTokenUser

test:
  path: /api/test
  controller: App\Controller\ApiController::test

## student end point declaration ##
##
##
student_get_detail:
  path: /student/api/user/get/{id}
  controller: App\Controller\UserController::getOneUser
  methods: GET
